name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'  # Ensure your gems support Ruby 3.3
      - name: Install dependencies
        run: |
          gem install bundler  # Ensure bundler is installed
          bundle install        # Install dependencies from Gemfile
          bundle exec appraisal install  # Install appraisal gemfiles (if using appraisal)
      - name: Build site
        run: |
          bundle exec jekyll build --future  # Build the Jekyll site (without appraisal unless necessary)

